Feature: feature001

  Scenario Outline: To verify Sales rep is able to perform an E2E with (data, voice & data(individual), voice & data(shared)) products in Pre Prod
    Given User logins as Enterprise Sales representative for GPT
    Then Sales rep for GPT creates an opportunity with the following details "<Account_Name>""<Deal_Type>" "<Type_of_support>"
    Then Sales rep for GPT adds the Enterprise product details for all DPT products
      |Product_Category  |Product                         |Product_Detail |Mobile_Tariffs |Mobile_Services|Quans  |LOC |Billed_Upfront|Revenue_per_month |Business_Type   |
      |Mobile            |Voice & Data                    |Voice & Data   |Standard       |Standard       |200    |1   |500           |15000             |New / Additional|
    Then Sales rep for GPT creates a product basket to add GPT products
    Then Sales rep for GPT configures GPT product one in the basket with the following details"<NoOfConnections1>" "<ProvisionalTarrif1>" "<BillSpendCap1>" "<PrivateAPN1>" "<MobexRequired1>" "<MobexService1>" "<Type1>" "<VoiceType1>" "<Term1>" "<DataType1>" "<DataAllowance1>" "<CappedOrUncapped1>" "<AggregatedData1>"
    Then Sales rep for GPT configures GPT product two in the basket with the following details"<NoOfConnections2>" "<ProvisionalTarrif2>" "<BillSpendCap2>" "<PrivateAPN2>" "<MobexRequired2>" "<MobexService2>" "<Type2>" "<VoiceType2>" "<DataType2>" "<DataAllowance2>" "<CappedOrUncapped2>" "<AggregatedData2>"
    Then Sales rep for GPT configures GPT product three in the basket with the following details"<NoOfConnections3>" "<ProvisionalTarrif3>" "<BillSpendCap3>" "<PrivateAPN3>" "<MobexRequired3>" "<MobexService3>" "<Type3>" "<VoiceType3>" "<DataType3>" "<DataAllowance3>" "<CappedOrUncapped3>" "<AggregatedData3>"
    Then Sales representative for GPT configures Resign details"<Connections_Resign>" "<Revenue_Resign>"
    Then Sales representative for GPT configures Call mix details"<International_and_Roaming_Rates>"
    Then Sales rep for GPT visits Clauses section to update the required details"<TF>"
    Then Sales rep for GPT verifies the discount section"<Voice_Discount1>" "<Voice_Discount2>" "<Voice_Discount3>" "<Data_Discount1>" "<Data_Discount2>" "<Data_Discount3>" "<Sharer_Fee3>"
    Then Sales rep for GPT views the Profit and Loss section for the configured GPT products
    Then Sales rep for GPT validates the basket page
    Then Sales rep for GPT submits basket for approval and Financial approvers for GPT approve the basket and the basket is synced with the opportunity
    Then User logs in as Sales Rep to change the opportunity stage as Awareness of needs inorder to kick off the Sales governance process for GPT products
    Then Sales Rep for GPT feeds in the details in Agreement to support stage
    Then User logins as Qgate Admin to approve Agreement to support stage for GPT
    Then User logins as Qgate admin to approve Solution and Delivery of GPT QA Stage
    Then User logins as Sales Rep to feed in the data in Agreement to Propose stage with the following details for GPT products "<Submission_type>"  "<Contract_terms>"  "<Service_levels>"
    Then User logins as Qgate Admin to approve Agreement to propose stage for GPT products
    Then User logins as Sales Rep to change the Opportunity stage as decision for configured GPT products
    Then User logins as Sales Rep to feed in thr details in Agreement to sign stage for GPT products
    Then User logins as Qgate admin to approve Agreement to sign stage for GPT products
    Then User logins as Sales Rep to feed in the details in Acceptance into delivery stage for GPT products
    Then User logins as Qgate Admin to approve Acceptance into delivery stage for GPT products
    Then User logins as Sales Rep to feed in the details in Acceptance into service stage for GPT products
    Then User logins as Qgate Admin to approve Acceptance into service stage for GPT products

    Examples:
      |Scenario_Identifier |Account_Name  | Deal_Type  | Type_of_support         | NoOfConnections1   | ProvisionalTarrif1  | BillSpendCap1 |PrivateAPN1|MobexRequired1|MobexService1|Type1         |VoiceType1|Term1|DataType1  |DataAllowance1    |CappedOrUncapped1|AggregatedData1| NoOfConnections2   | ProvisionalTarrif2  | BillSpendCap2 |PrivateAPN2|MobexRequired2|MobexService2|Type2         |VoiceType2|DataType2  |DataAllowance2  |CappedOrUncapped2|AggregatedData2|NoOfConnections3    | ProvisionalTarrif3  | BillSpendCap3 |PrivateAPN3|MobexRequired3|MobexService3|Type3         |VoiceType3|DataType3  |DataAllowance3    |CappedOrUncapped3|AggregatedData3|Connections_Resign|Revenue_Resign|International_and_Roaming_Rates|TF  |Voice_Discount1|Voice_Discount2|Voice_Discount3|Data_Discount1|Data_Discount2|Data_Discount3|Sharer_Fee3|Submission_type   |Contract_terms         |Service_levels|
      |Configuration 029_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |1GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |1GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.37          |12.37          |4.66          |1.66          |19704.89      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 029_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |1GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |1GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.96          |12.96          |5.18          |2.18          |21992.69      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 029_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |1GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |1GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.25          |13.25          |5.44          |2.44          |23136.60      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 029_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |1GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |1GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.54          |13.54          |5.7           |2.7           |24280.5       |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 030_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |2GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |2GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5.5TB Shared Data |Uncapped         |               |                  |              |Standard rates                 |    |               |12.6           |12.6           |7.1           |4.1           |22932.45      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 030_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |2GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |2GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5.5TB Shared Data |Uncapped         |               |                  |              |Standard rates                 |    |               |13.13          |13.13          |7.74          |4.74          |25169.68      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 030_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |2GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |2GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5.5TB Shared Data |Uncapped         |               |                  |              |Standard rates                 |    |               |13.4           |13.4           |8.07          |5.07          |26288.3       |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 030_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |2GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |2GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |5.5TB Shared Data |Uncapped         |               |                  |              |Standard rates                 |    |               |13.66          |13.66          |8.39          |5.39          |27406.91      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 031_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |3GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |3GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |6TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.15          |12.15          |8.44          |5.44          |23351.89      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 031_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |3GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |3GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |6TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.78          |12.78          |9.45          |6.45          |26162.58      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 031_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |3GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |3GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |6TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.1           |13.1           |9.96          |6.96          |27567.93      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 031_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |3GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |3GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |6TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.42          |13.42          |10.46         |7.46          |28973.27      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 032_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |4GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |4GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |7TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.37          |12.37          |9.78          |6.78          |29221.45      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 032_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |4GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |4GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |7TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.96          |12.96          |10.94         |7.94          |32061.43      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 032_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |4GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |4GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |7TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.25          |13.25          |11.52         |8.52          |33480.97      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 032_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |24   |Individual |4GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |4GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |7TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.54          |13.54          |12.1          |9.1           |34900.81      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 033_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |5GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |5GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |8TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.6           |12.6           |11.45         |8.45          |34854.85      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 033_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |5GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |5GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |8TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.13          |13.13          |12.69         |9.69          |37775.99      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 033_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |5GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |5GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |8TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.4           |13.4           |13.3          |10.3          |39236.56      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 033_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |36   |Individual |5GB               |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |5GB             |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |8TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.66          |13.66          |13.92         |10.92         |40697.14      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 034_1 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |10GB              |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |10GB            |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |9TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.15          |12.15          |3.98          |0.98          |18775.38      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 034_2 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |10GB              |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |10GB            |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |9TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |12.78          |12.78          |5.99          |2.99          |22603.07      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 034_3 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |10GB              |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |10GB            |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |9TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.1           |13.1           |6.99          |3.99          |24516.92      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
      |Configuration 034_4 |Test Private  | Acquisition| Self-serve pricing tools| 500                | No                  | No            |No         |No            |             |Data Only     |Unlimited |12   |Individual |10GB              |Uncapped         |               | 1500               | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Individual |10GB            |Uncapped         |               |500                 | No                  | No            |No         |No            |             |Voice & Data  |Unlimited |Shared     |9TB Shared Data   |Uncapped         |               |                  |              |Standard rates                 |    |               |13.42          |13.42          |7.99          |4.99          |26430.77      |           | First submission |Standard TEF UK Ts & Cs|Standard      |
