Feature: feature001

  Scenario Outline: To verify Sales rep is able to add and validate the basket in Pre Prod
    Given User logins as Enterprise Sales representative for DPT
    Then Sales rep for DPT creates an opportunity with the following details "<Deal_Type>" "<Type_of_support>"
    Then Sales rep for DPT adds the Enterprise product details for all DDP products
      |Product_Category  |Product                         |Product_Detail |Mobile_Tariffs |Mobile_Services|Quans  |LOC |Billed_Upfront|Revenue_per_month |Business_Type   |
      |Mobile            |Voice & Data                    |Voice & Data   |Standard       |Standard       |200    |1   |500           |15000             |New / Additional|
    Then Sales rep for DPT creates a product basket to add DDP products
    Then Sales rep for DPT configures all DPT products in the basket with the following details"<NoOfConnections>" "<ProvisionalTarrif>" "<BillSpendCap>" "<PrivateAPN>" "<MobexRequired>" "<MobexService>" "<Type>" "<VoiceType>" "<Term>" "<DataType>" "<DataAllowance>" "<CappedOrUncapped>" "<AggregatedData>"
    Then Sales representative configures Resign details"<Connections_Resign>" "<Revenue_Resign>"
    Then Sales representative configures Call mix details
    Then Sales rep for DPT visits Clauses section to update the required details"<TF>"
    Then Sales rep for DPT verifies the discount section
    Then Sales rep for DPT views the Profit and Loss section for the configured DPT products
    Then Sales rep for DPT validates the basket page
    Then Sales rep for DPT submits basket for approval and Financial approvers for DPT approve the basket and the basket is synced with the opportunity

    Examples:
      |Scenario_Identifier |Account_Name  | Deal_Type  | Type_of_support         | NoOfConnections   | ProvisionalTarrif  | BillSpendCap |PrivateAPN|MobexRequired|MobexService|Type         |VoiceType|Term|DataType  |DataAllowance  |CappedOrUncapped|AggregatedData|Connections_Resign|Revenue_Resign|TF |
      |ID_318 ID_319 ID_320|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_321 ID_322 ID_323|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_324 ID_325 ID_326|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_327 ID_328 ID_329|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_330 ID_331 ID_332|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_333 ID_334 ID_335|Test Private  | Acquisition| Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_336 ID_337 ID_338|Test Private  | Acquisition| Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |                  |              |100|
      |ID_339 ID_340 ID_341|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_342 ID_343 ID_344|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_345 ID_346 ID_347|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_348 ID_349 ID_350|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_351 ID_352 ID_353|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_354 ID_355 ID_356|Test Private  | Acquisition| Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_357 ID_358 ID_359|Test Private  | Acquisition| Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_360 ID_361 ID_362|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_363 ID_364 ID_365|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_366 ID_367 ID_368|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_369 ID_370 ID_371|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_372 ID_373 ID_374|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_375 ID_376 ID_377|Test Private  | Acquisition| Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_378 ID_379 ID_380|Test Private  | Acquisition| Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_381 ID_382 ID_383|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_384 ID_385 ID_386|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_387 ID_388 ID_389|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_390 ID_391 ID_392|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_393 ID_394 ID_395|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_396 ID_397 ID_398|Test Private  | Acquisition| Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_399 ID_400 ID_401|Test Private  | Acquisition| Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_402 ID_403 ID_404|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_405 ID_406 ID_407|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_408 ID_409 ID_410|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_411 ID_412 ID_413|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_414 ID_415 ID_416|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_417 ID_418 ID_419|Test Private  | Acquisition| Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_420 ID_421 ID_422|Test Private  | Acquisition| Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_423 ID_424 ID_425|Test Private  | Acquisition| Self-serve pricing tools| 4000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_426 ID_427 ID_428|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |                  |              |100|
      |ID_429 ID_430 ID_431|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |                  |              |100|
      |ID_432 ID_433 ID_434|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |                  |              |100|
      |ID_435 ID_436 ID_437|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |                  |              |100|
      |ID_438 ID_439 ID_440|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |                  |              |100|
      |ID_441 ID_442 ID_443|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |                  |              |100|
      |ID_444 ID_445 ID_446|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |                  |              |100|
      |ID_447 ID_448 ID_449|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |                  |              |100|
      |ID_450 ID_451 ID_452|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |                  |              |100|
      |ID_453 ID_454 ID_455|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |                  |              |100|
      |ID_456 ID_457 ID_458|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_459 ID_460 ID_461|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_462 ID_463 ID_464|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_465 ID_466 ID_467|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_468 ID_469 ID_470|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |                  |              |100|
      |ID_471 ID_472 ID_473|Test Private  | Acquisition| Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_474 ID_475 ID_476|Test Private  | Acquisition| Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Capped          |              |                  |              |100|
      |ID_477 ID_478 ID_479|Test Private  | Acquisition| Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_480 ID_481 ID_482|Test Private  | Acquisition| Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_483 ID_484 ID_485|Test Private  | Acquisition| Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |                  |              |100|
      |ID_486 ID_487 ID_488|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |300               |100000        |100|
      |ID_489 ID_490 ID_491|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |800               |100000        |100|
      |ID_492 ID_493 ID_494|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |1300              |100000        |100|
      |ID_495 ID_496 ID_497|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |1800              |100000        |100|
      |ID_498 ID_499 ID_500|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |2300              |100000        |100|
      |ID_501 ID_502 ID_503|Test Private  | Resign     | Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |2800              |100000        |100|
      |ID_504 ID_505 ID_506|Test Private  | Resign     | Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Pay per MB|               |                |              |3300              |100000        |100|
      |ID_507 ID_508 ID_509|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |700               |100000        |100|
      |ID_510 ID_511 ID_512|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |1200              |100000        |100|
      |ID_513 ID_514 ID_515|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |1700              |100000        |100|
      |ID_516 ID_517 ID_518|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |2200              |100000        |100|
      |ID_519 ID_520 ID_521|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |2700              |100000        |100|
      |ID_522 ID_523 ID_524|Test Private  | Resign     | Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |3200              |100000        |100|
      |ID_525 ID_526 ID_527|Test Private  | Resign     | Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Capped          |              |3700              |100000        |100|
      |ID_528 ID_529 ID_530|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |300               |100000        |100|
      |ID_531 ID_532 ID_533|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |800               |100000        |100|
      |ID_534 ID_535 ID_536|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |1300              |100000        |100|
      |ID_537 ID_538 ID_539|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |1800              |100000        |100|
      |ID_540 ID_541 ID_542|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |2300              |100000        |100|
      |ID_543 ID_544 ID_545|Test Private  | Resign     | Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |2800              |100000        |100|
      |ID_546 ID_547 ID_548|Test Private  | Resign     | Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Individual|10GB           |Uncapped        |              |3300              |100000        |100|
      |ID_549 ID_550 ID_551|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |700               |100000        |100|
      |ID_552 ID_553 ID_554|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |1200              |100000        |100|
      |ID_555 ID_556 ID_557|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |1700              |100000        |100|
      |ID_558 ID_559 ID_560|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |1TB Shared Data|Uncapped        |              |2200              |100000        |100|
      |ID_561 ID_562 ID_563|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |2700              |100000        |100|
      |ID_564 ID_565 ID_566|Test Private  | Resign     | Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |3200              |100000        |100|
      |ID_567 ID_568 ID_569|Test Private  | Resign     | Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |PAYU     |24  |Shared    |2TB Shared Data|Uncapped        |              |3700              |100000        |100|
      |ID_570 ID_571 ID_572|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |300               |100000        |100|
      |ID_573 ID_574 ID_575|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |800               |100000        |100|
      |ID_576 ID_577 ID_578|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |1300              |100000        |100|
      |ID_579 ID_580 ID_581|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Capped          |              |1800              |100000        |100|
      |ID_582 ID_583 ID_584|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |2300              |100000        |100|
      |ID_585 ID_586 ID_587|Test Private  | Resign     | Self-serve pricing tools| 3000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |2800              |100000        |100|
      |ID_588 ID_589 ID_590|Test Private  | Resign     | Self-serve pricing tools| 3500              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |3300              |100000        |100|
      |ID_591 ID_592 ID_593|Test Private  | Resign     | Self-serve pricing tools| 4000              | No                 | No           |No        |No           |            |Voice & Data |Unlimited|24  |Individual|10GB           |Uncapped        |              |3800              |100000        |100|
      |ID_594 ID_595 ID_596|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |700               |100000        |100|
      |ID_597 ID_598 ID_599|Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |1200              |100000        |100|
      |ID_600 ID_601 ID_602|Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |1700              |100000        |100|
      |ID_603 ID_604 ID_605|Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |2200              |100000        |100|
      |ID_606 ID_607 ID_608|Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice Only   |PAYU     |24  |          |               |                |              |2700              |100000        |100|
      |ID_609 ID_610 ID_611|Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |300               |100000        |100|
      |ID_612 ID_613       |Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |800               |100000        |100|
      |ID_614              |Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |1300              |100000        |100|
      |ID_615              |Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |1800              |100000        |100|
      |ID_616              |Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Voice Only   |Unlimited|24  |          |               |                |              |2300              |100000        |100|
      |ID_617              |Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |700               |100000        |100|
      |ID_618              |Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |1200              |100000        |100|
      |ID_619              |Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |1700              |100000        |100|
      |ID_620              |Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |2200              |100000        |100|
      |ID_621              |Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Shared    |1TB Shared Data|Uncapped        |              |2700              |100000        |100|
      |ID_622              |Test Private  | Resign     | Self-serve pricing tools| 500               | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Capped          |              |300               |100000        |100|
      |ID_623              |Test Private  | Resign     | Self-serve pricing tools| 1000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Capped          |              |800               |100000        |100|
      |ID_624              |Test Private  | Resign     | Self-serve pricing tools| 1500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |1300              |100000        |100|
      |ID_625              |Test Private  | Resign     | Self-serve pricing tools| 2000              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |1800              |100000        |100|
      |ID_626              |Test Private  | Resign     | Self-serve pricing tools| 2500              | No                 | No           |No        |No           |            |Data Only    |         |24  |Individual|10GB           |Uncapped        |              |2300              |100000        |100|
